PetSearcher/Controllers/NoticeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PetSearcher.Helper;
using PetSearcher.Models;
using PetSearcher.Models.ViewModels;
using PetSearcher.Services;

namespace PetSearcher.Controllers
{
    
    public class NoticeController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly INoticeService _noticeService;
        private readonly UserManager<ApplicationUser> _userManager;

        public NoticeController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment, INoticeService noticeService, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            _noticeService = noticeService;
            _userManager = userManager;
        }


        public async Task<IActionResult> Index()
        {
            ViewBag.PhoneNumbers = _noticeService.GetUsersPhonesList();
            ViewBag.UserId = _userManager.GetUserId(HttpContext.User);

            return _context.Notices != null ? 
                          View(await _context.Notices.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Notices'  is null.");
        }

       
        public async Task<IActionResult> Details(int? id)
        {
            ViewBag.PhoneNumbers = _noticeService.GetUsersPhonesList();
            if (id == null || _context.Notices == null)
            {
                return NotFound();
            }

            var notice = await _context.Notices
                .FirstOrDefaultAsync(m => m.Id == id);
            if (notice == null)
            {
                return NotFound();
            }

            return View(notice);
        }

       
        [Authorize]
        public IActionResult Create()
        {
            ViewBag.PetTypesList = HelperClass.GetRolesForDropDown();
            return View();
        }

       
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Notice notice)
        {
            if(notice.Privacy == false)
            {
                ModelState.AddModelError(nameof(notice.Privacy), "Необходимо согласие с политикой конфиденциальности");
            }
            if (ModelState.IsValid)
            {   
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(notice.ImageFile.FileName);
                string fileExtension = Path.GetExtension(notice.ImageFile.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + fileExtension;
                string path = Path.Combine(wwwRootPath + "/Image/", fileName);
                notice.ImagePath = path;
                notice.ImageName = fileName;
                using(var filestream = new FileStream(path, FileMode.Create))
                {
                    await notice.ImageFile.CopyToAsync(filestream);
                }
                notice.UserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                   



                _context.Add(notice);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(notice);
        }

       
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Notices == null)
            {
                return NotFound();
            }

            var DBnotice = await _context.Notices.FindAsync(id);
            if (DBnotice == null)
            {
                return NotFound();
            }
            EditNoticeViewModel notice = new EditNoticeViewModel();
            notice.Location = DBnotice.Location;
            notice.Name = DBnotice.Name;
            notice.Description = DBnotice.Description;
            return View(notice);
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, EditNoticeViewModel notice)
        {
            //if (id != notice.Id)
            //{
            //    return NotFound();
            //}
            if (_context.Notices == null)
            {
                return NotFound();
            }
            var DBnotice = await _context.Notices.FindAsync(id);
            if ( DBnotice != null)
            {
                
                DBnotice.Name = notice.Name;
                DBnotice.Description = notice.Description;
                DBnotice.Location = notice.Location;
               
            }
            else
            {
                return NotFound();
            }
            if (_userManager.GetUserId(HttpContext.User) == DBnotice.UserId || User.IsInRole("Support"))
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(DBnotice);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!NoticeExists(id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
            }
            else
            {
                return NotFound();
            }
            return View(notice);
        }

        
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Notices == null)
            {
                return NotFound();
            }

            var notice = await _context.Notices
                .FirstOrDefaultAsync(m => m.Id == id);
            if (notice == null)
            {
                return NotFound();
            }

            return View(notice);
        }

        
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            
            if (_context.Notices == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Notices'  is null.");
            }
            var notice = await _context.Notices.FindAsync(id);
            if (notice != null)
            {
                if (_userManager.GetUserId(HttpContext.User) == notice.UserId || User.IsInRole("Support"))
                {
                    if (System.IO.File.Exists(notice.ImagePath))
                    {
                        System.IO.File.Delete(notice.ImagePath);
                    }
                    _context.Notices.Remove(notice);
                }
                else
                {
                    return Problem("Error: You are not owner of this notice.");
                }
            }
            

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NoticeExists(int id)
        {
          return (_context.Notices?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        [Authorize]
        public IActionResult MyNotices()
        {
            ViewBag.PhoneNumbers = _noticeService.GetUsersPhonesList();
            var UserID = _userManager.GetUserId(HttpContext.User);
            var NoticeList = new List<Notice>();
            if (_context.Notices != null)
            { 
                foreach (var notice in _context.Notices)
                {
                    if(notice.UserId == UserID)
                    {
                        NoticeList.Add(notice);
                    }
                }


            }
            return View(NoticeList);
        }
    }
}

PetSearcher/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Identity.SignInManager<ApplicationUser> signInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PetSearcher</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PetSearcher.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-secondary border-bottom box-shadow mb-3 ">
            <div class="container-fluid">
                <a class="navbar-brand text-white dzerix-brand" asp-area="" asp-controller="Notice" asp-action="Index">PetSearcher</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Notice" asp-action="Index">Объявления</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">О нас</a>
                        </li>
                    </ul>

                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PetSearcher - <a asp-area="" asp-controller="Home" asp-action="Privacy">Политика конфиденциальности</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script>
        @await RenderSectionAsync("Scripts", required: false)
    </script>
    
    
</body>
</html>